const lessons = [
[1,"Your real starting point","Health is not a photo or a number. It is how your body and mind help you live, study, work, play and rest.","Kabir gets tired climbing stairs but sleeps well. His first goal can be stronger legs, not a scale number.","Write: energy today 1–5, sleep hours, and one thing you already do well.","Did I observe myself without calling myself lazy or bad?"],
[2,"The four body signals","Notice hunger, fullness, thirst and tiredness. They are messages, not enemies.","Neha thinks she wants chips at 5 pm. After water and a banana, she realises she was hungry, not just bored.","Before one snack today, pause for 10 seconds and name the signal you feel.","What signal did I notice?"],
[3,"Make your why","A good goal tells you what life will feel easier, not only what you want to look like.","Instead of “I must lose weight,” Aman writes, “I want enough energy to play cricket on Sundays.”","Finish this sentence: “I want to care for my health because…”","Is my reason kind and useful?"],
[4,"Tiny beats huge","A tiny action is easier to repeat. Repetition teaches your brain, “this is normal.”","Ten minutes of walking after lunch is easier to continue than promising a two-hour workout.","Choose one action that takes under 10 minutes and do it today.","Could I repeat this tomorrow?"],
[5,"Your daily rhythm","Bodies like some regularity: eating, moving and sleeping at roughly similar times.","Sara eats lunch at 1 pm most days, so she keeps fruit at 4 pm instead of reaching for random snacks.","Draw your normal day from wake-up to bedtime. Circle one difficult time.","Which time needs a simple plan?"],
[6,"Water without myths","Water helps normal body functions. You do not need to force huge amounts or follow a magic number.","Rohan carries a bottle to school and drinks when thirsty, with meals, and after play.","Keep water where you can see it. Have one glass with a meal.","Did I make water easy to remember?"],
[7,"Food is not a reward","Food gives energy and enjoyment. Calling food “good” or “bad” can create guilt.","Priya enjoys ice cream at a party, then has her normal dinner. She does not punish herself by skipping food.","Notice one food thought today. Replace “I was bad” with “I made a choice.”","Did I speak about food with respect?"],
[8,"A simple baseline walk","Walking is a useful beginner movement because it needs little equipment.","Vikram walks for 8 minutes around his building after dinner, at a pace where he can still talk.","Walk easily for 8–10 minutes. Stop if you feel pain, dizziness or unwell.","Could I talk while walking?"],
[9,"Sleep is a recharge","During sleep your brain and body recover. Sleep is not wasted time.","After sleeping 5 hours, Isha finds it harder to focus and wants quick sugary snacks. After a regular bedtime, mornings feel easier.","Pick a realistic lights-out time for tonight.","What could help me start winding down?"],
[10,"Your first review","Reviewing means learning, not judging. A plan can be changed.","Dev missed two walks because it rained. He chooses indoor marching instead of giving up.","Write one win, one hard moment, and one adjustment for the next 10 days.","What will I keep? What will I change?"],
[11,"Build a balanced plate","A simple plate has vegetables or fruit, a protein food, and an energy food such as roti, rice, potato or millet.","Lunch: dal, two rotis, cucumber-carrot salad and curd. It has more variety than only rotis and pickle.","Look at one meal. Add one missing group if it is available.","Which group did my meal need?"],
[12,"Protein is the repair team","Protein helps build and repair body tissues. Common choices include dal, beans, curd, paneer, eggs, soy, fish and chicken.","Poha becomes more filling with peanuts and curd; an egg sandwich adds protein to toast.","Add one familiar protein food to one meal.","What protein did I choose?"],
[13,"Fibre is the helper","Fibre is found in plant foods. It supports digestion and can help you feel full.","Whole orange gives fibre; orange juice has much less fibre because the pulp is removed.","Eat one fruit, vegetable, bean or whole grain today.","Which plant food did I add?"],
[14,"Colour on the plate","Different-coloured plants contain different helpful nutrients. You do not need a rainbow every meal.","Green spinach, orange carrot, red tomato and purple beetroot can be mixed across a week.","Add one colour to lunch or dinner.","What colour did I add?"],
[15,"Carbohydrates give fuel","Rice, roti, potato, oats, corn and millet give energy. They are not the enemy.","A football player needs fuel; the helpful question is what else is on the plate, not “is rice forbidden?”","Eat your usual carbohydrate with protein or vegetables, not with guilt.","Did I make the meal more balanced?"],
[16,"Fats have jobs too","Nuts, seeds, oils, avocado, fish and dairy contain fats. Amount and variety matter.","A small handful of peanuts in poha adds flavour and staying power; deep-fried snacks every day are different.","Notice one fat source in your food today. No need to remove it.","Did I choose with awareness, not fear?"],
[17,"Plan an easy breakfast","Breakfast is optional for some people, but if you are hungry in the morning, make it more filling than tea and biscuits.","Options: vegetable poha with peanuts, idli with sambar, eggs and toast, or oats with curd and fruit.","Plan tomorrow’s breakfast or first meal tonight.","Is there protein or fibre in it?"],
[18,"Snack with a purpose","A snack can bridge a long gap between meals. It is not a failure.","At 4 pm, fruit with curd or roasted chana helps Maya reach dinner calmly.","Prepare one simple snack: fruit, nuts, curd, chana, sprouts, or leftovers.","Will this help my actual hunger?"],
[19,"Eat slowly enough to notice","Your body needs time to tell your brain it is getting full.","Instead of eating while watching reels, Jay sits at the table for the first five bites and notices taste.","For one meal, put the screen away for five minutes.","What did I notice about taste or fullness?"],
[20,"Food review: normal meals","The best food plan is one you can afford, enjoy and repeat.","Rather than buying expensive powders, Farah uses dal, seasonal vegetables, eggs and curd.","Write three everyday meals you enjoy. Give each a simple balance upgrade.","Which meal feels easiest to repeat?"],
[21,"Movement has four parts","A healthy movement mix can include walking, strength, mobility and rest. You do not need to do all at once.","Walking helps stamina; chair-squats build leg strength; stretching helps comfortable movement.","Choose the one type you do least and try a gentle version.","Which movement type did I try?"],
[22,"Sitting breaks","Long sitting can make your body feel stiff. Short movement breaks help.","Every hour of homework, Anil stands, reaches up and walks to refill water for two minutes.","Set two reminders today to stand and move for two minutes.","Did my body feel different after the break?"],
[23,"Walk at your level","The right walk is one you can recover from. Faster is not always better.","Lina starts with 10 minutes three times a week. Next week she adds only two minutes.","Pick a time and place for an easy 10-minute walk.","Could I finish without pain or gasping?"],
[24,"Learn the chair-squat","A squat is like sitting and standing. Use a sturdy chair for support.","Feet under knees, stand up slowly, then sit with control. Hold a wall or chair if needed.","Do 5 slow chair-squats only if comfortable. Stop for pain.","Did my knees and back feel okay?"],
[25,"Learn the wall push-up","Wall push-ups can strengthen arms and chest with less pressure than floor push-ups.","Hands on wall at chest height, body straight, bend elbows gently, push away.","Try 5 wall push-ups at a comfortable distance from the wall.","Could I move smoothly?"],
[26,"Strong core means steady","Your core includes muscles around the middle of your body. It helps you stand, carry and move.","When carrying a school bag, a steady middle helps you stay upright. You do not need endless crunches.","Practise standing tall: ribs relaxed, shoulders easy, breathe normally for 30 seconds.","Could I stand tall without holding my breath?"],
[27,"Mobility is easy movement","Mobility means moving joints comfortably through their range. It is not forcing a painful stretch.","Shoulder circles before carrying groceries can make arms feel less stiff.","Do 5 gentle shoulder circles and 5 ankle circles each side.","Did I stay gentle, not forceful?"],
[28,"Rest is part of training","Muscles and energy need recovery. More exercise is not always more progress.","After a new workout, Sameer rests the next day and takes an easy walk instead.","Choose one recovery action: easy walk, gentle stretch, early bedtime, or rest.","What did recovery feel like?"],
[29,"Make movement enjoyable","You are more likely to repeat movement you do not hate.","Nisha dances to two favourite songs instead of forcing a boring workout video.","Choose music, a friend, a route, or a game that makes movement nicer.","What made it more enjoyable?"],
[30,"Movement review","Progress can mean more confidence, not only more minutes or repetitions.","On Day 23, 10 minutes felt hard. On Day 30, Rahul can walk it while talking.","Write one movement you can do now or understand better.","What is my next safe step?"],
[31,"Stress is an alarm","Stress is the body preparing for a challenge. Too much, for too long, can feel exhausting.","Before an exam, heart rate rises and thoughts race. A slow pause helps the alarm settle.","Name one current stressor without trying to solve it yet.","What is making my alarm loud?"],
[32,"The 60-second breathing pause","Slow breathing can help you pause before reacting. It is not a cure for all stress.","Before replying angrily, Tariq breathes in gently and makes the out-breath a little longer.","For one minute: breathe comfortably in, then breathe out slowly. Stop if dizzy.","Did my shoulders soften even a little?"],
[33,"Create a sleep landing strip","A landing strip is a short routine that tells your brain bedtime is coming.","At 10:30, Asha charges her phone away, washes her face, and reads two pages.","Choose two calm actions for the 20 minutes before bed.","What will I do first tonight?"],
[34,"Light and screens","Bright screens late at night can keep some brains alert. Small changes are enough.","Ravi changes from reels in bed to music with the phone across the room.","Keep your phone out of reach for the last 15 minutes before sleep.","What can replace scrolling?"],
[35,"Caffeine timing","Tea, coffee and energy drinks can affect sleep, especially later in the day.","Mehul cannot sleep after strong coffee at 7 pm, so he shifts it earlier or chooses a non-caffeinated drink.","Notice when you last have caffeine today. Do not change prescribed or needed routines without advice.","Did it affect my sleep?"],
[36,"Cravings need curiosity","A craving can come from hunger, tiredness, habit, emotion, or seeing food. It is normal.","After skipping lunch, Pooja wants sweets at 6 pm. A proper snack helps more than self-blame.","When a craving comes, ask: hungry, tired, stressed, or simply wanting taste?","What answer did I find?"],
[37,"Make your room help you","Your surroundings influence choices. Change the easiest thing first.","A water bottle on the desk is easier to use than one hidden in a cupboard.","Set up one helpful cue: shoes by the door, fruit visible, or phone charger away from bed.","What cue did I set?"],
[38,"Talk to yourself like a coach","Harsh words usually make recovery harder. A coach notices, adjusts, and continues.","Instead of “I ruined everything,” say, “Today was hard. My next meal can be normal.”","Write one kind sentence you can use after a tough day.","Would I say this to a friend?"],
[39,"Ask for support","Health habits are easier when someone knows your plan.","Irfan tells his sister he wants a 10-minute walk after dinner. She joins twice this week.","Tell one trusted person one small habit you are practising.","What support would actually help?"],
[40,"Reset review","A reset does not mean erasing your life. It means returning to the next helpful choice.","After a late night and takeout, Kavya drinks water, eats breakfast, and takes an easy walk the next day.","Choose your personal reset action for rough days.","Can I do it without punishment?"],
[41,"Habits need a cue","A cue is the moment that reminds you to act.","“After I brush my teeth, I fill my bottle” is clearer than “I will drink more water.”","Write one ‘After I…, I will…’ plan.","What is my exact cue?"],
[42,"Make good choices easy","Willpower is limited. Arrange your space so the helpful option is nearby.","Sliced fruit at eye level is easier than fruit hidden at the back of the fridge.","Prepare one helpful option before you need it.","What did I make easier?"],
[43,"Make hard choices less automatic","You do not need to ban food or fun. Add a small pause to an unhelpful habit.","Instead of keeping chips beside the desk, keep them in the kitchen and choose a bowl if you want some.","Move one temptation out of your direct view.","What pause did I create?"],
[44,"Use a weekly plan, not a perfect plan","A plan gives choices before you are tired or busy.","Sunday plan: walk Mon/Wed/Fri; keep eggs, dal and fruit at home; one flexible meal out.","Write three realistic actions for the next seven days.","Does this fit my real schedule?"],
[45,"The 80% idea","Most meals and days can support your goals; some can simply be enjoyable or convenient.","At a wedding, Zoya enjoys dinner. The next morning she returns to her usual breakfast.","Name one flexible situation you may face this week and your calm response.","How will I avoid all-or-nothing thinking?"],
[46,"Track only what helps","Tracking is useful if it teaches you something. It is not useful if it makes you anxious.","Arman checks off walks on a calendar; he does not weigh himself every day.","Pick one helpful measure: walks, bedtime, vegetables, mood, or water habits.","What does my tracker teach me?"],
[47,"Solve the ‘too busy’ problem","When time is tight, shrink the habit instead of deleting it.","No time for a walk? Priyanka walks five minutes while talking on a call.","Create a 2-minute version of your main habit.","What is my smallest version?"],
[48,"Plan for travel and celebrations","A routine can bend without breaking.","On a trip, Rakesh drinks water, chooses a filling breakfast, and walks when possible. He does not demand perfection.","Choose one travel or celebration anchor: water, fruit, walking, or regular breakfast.","What is my anchor?"],
[49,"Learn from a hard day","A hard day has clues: missing food, too little sleep, stress, no planning, or unrealistic goals.","After evening overeating, Sheetal sees she had only tea since lunch. Tomorrow she packs a snack.","Write: What happened? What might help next time?","Did I learn instead of blame?"],
[50,"Habit review","Keep habits that feel useful and possible. Drop the ones that only create pressure.","Vivek keeps the after-dinner walk but stops forcing a 5 am wake-up that ruins sleep.","Circle your best two habits from Days 41–50.","Why do these fit my life?"],
[51,"Choose your three anchors","Anchors are small habits that hold your week together: food, movement, and rest.","An anchor set: protein at breakfast, 15-minute walk three days, phone away at 11 pm.","Choose one food, one movement and one recovery anchor.","Are all three truly realistic?"],
[52,"Create a simple weekday plan","A weekday plan protects choices before life gets busy.","Monday: pack fruit; walk at 7 pm; prepare clothes for bed routine.","Write tomorrow’s food, movement, and sleep cue in one line each.","What could get in the way?"],
[53,"Create a simple weekend plan","Weekends can change rhythm. Give yourself one or two anchors, not a strict timetable.","On Sunday, Neel sleeps a little later but still eats breakfast and walks with family.","Pick two weekend anchors.","Will this leave room for rest and fun?"],
[54,"Build your support map","Different people can support different needs.","A friend can be a walking buddy; a doctor answers medical questions; family can help with groceries.","List one person for encouragement and one professional to ask if health concerns arise.","Who is on my team?"],
[55,"Know when to get help","Severe pain, fainting, chest pain, breathing trouble, eating distress, or major mood changes need professional help, not a challenge plan.","If a workout causes chest pain, stop and seek urgent medical advice instead of pushing through.","Write the name or number of a local clinic, trusted adult, or healthcare professional.","Do I know who to contact?"],
[56,"Your personal meal list","Make a short list of meals you can cook, buy or assemble.","Options: dal-rice-salad, egg bhurji-roti, curd rice with vegetables, chana chaat, or tofu stir-fry.","Write five meals that suit your budget, taste and routine.","Which one can I make on a busy day?"],
[57,"Your personal movement menu","A menu prevents the ‘I do not know what to do’ problem.","Menu: 10-minute walk, two songs of dance, chair-squats, wall push-ups, gentle stretching.","Write four safe activities you do not mind doing.","Which can I do indoors?"],
[58,"Your restart script","A restart script is a sentence you use after missing days.","“I do not need to catch up. I will do today’s smallest action.”","Write your own restart script on paper or your phone.","Does it sound kind and believable?"],
[59,"Celebrate skills, not just outcomes","Celebrate what you learned: planning, cooking, walking, resting, asking for help.","Mira celebrates packing snacks for a week, even though her schedule was chaotic.","List five skills or choices you are proud of.","What did I learn about myself?"],
[60,"Your next 30 days","The programme ends; learning continues. Repeat the habits that worked, then review monthly.","For the next month, Omar keeps his three anchors and checks in every Sunday.","Write a 30-day promise: my three anchors, my support person, and my restart script.","What is the first action I will take tomorrow?"]
];
const container = document.getElementById('daily-list');
container.innerHTML = lessons.map(([day,title,learn,example,action,check]) => `<article class="day-card" data-day="${day}" data-module="${Math.ceil(day / 10)}"><div class="day-number">DAY ${day}</div><figure class="lesson-visual" style="--visual-shift:${day * 17}deg;--visual-position:${(day * 13) % 100}% ${(day * 7) % 100}%"><img src="${visualForDay(day)}" alt="Illustration for Day ${day}: ${title}"><span class="visual-icon" aria-hidden="true">${visualIconForDay(day)}</span><figcaption>Day ${day} visual: ${title}</figcaption></figure><h3>${title}</h3><p><b>Learn:</b> ${learn}</p><p><b>Real-life example:</b> ${example}</p><p class="action"><b>Today’s small action:</b> ${action}</p><p class="check"><b>Quick check:</b> ${check}</p><div class="daily-media"><h4>Daily workout</h4><p>${workoutForDay(day)}</p><button type="button">Workout Video Placeholder</button><h4>Daily live session</h4><p>${liveSessionForDay(day,title)}</p><button type="button">Live Session Video Placeholder</button></div><!-- Day tracker removed --><details class="long-guide"><summary>Open the 1,000-word Day ${day} study guide</summary><div class="guide-content" data-day="${day}"></div></details></article>`).join('');
container.addEventListener('toggle', event => {
  const detail = event.target;
  if (!detail.matches('.long-guide') || !detail.open) return;
  const guide = detail.querySelector('.guide-content');
  if (guide.dataset.ready) return;
  const day = Number(guide.dataset.day);
  const lesson = lessons[day - 1];
  guide.innerHTML = fullGuide(...lesson);
  guide.dataset.ready = 'true';
}, true);
// Tracker removed.